name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.runner.version }} - ${{ matrix.runner.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.runner.os }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          # Current stable version
          - version: '1'
            os: ubuntu-latest
          # Minimum supported version
          - version: 'min'
            os: ubuntu-latest
          # macOS
          - version: '1'
            os: macOS-latest
          # Windows
          - version: '1'
            os: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.runner.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v7
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
